# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Anubhav Sachan
tagline:          'Learning with experience replay'
url:              https://anubhavsachan.com
baseurl:          ""

author:
  name:           'Anubhav Sachan'
  url:            https://anubhavsachan.com

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/anubhav4sachan/
  
medium:           https://medium.com/
  
plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /projects/:slug
  publications:
    output: true
    permalink: /projects/:slug
  notes:
    output: true
    permalink: /notes/:slug